-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Cursos"
(
    "Id" integer NOT NULL,
    "Codigo_curso" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nombre" character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "Cursos_pkey" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Alumnos_Cursos"
(
    "Id" integer NOT NULL,
    "IdCurso" integer,
    "IdAlumno" integer,
    CONSTRAINT "Alumnos_Cursos_pkey" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Alumnos"
(
    "Id" integer NOT NULL,
    "Nombres" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Apellidos" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Alumnos_pkey" PRIMARY KEY ("Id")
);

ALTER TABLE IF EXISTS public."Alumnos_Cursos"
    ADD FOREIGN KEY ("IdAlumno")
    REFERENCES public."Alumnos" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Alumnos_Cursos"
    ADD FOREIGN KEY ("IdCurso")
    REFERENCES public."Cursos" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;